number_of_steps = 1000

initial_population_healthy = 150
initial_population_infected = 1
infection_radius = 1e9
human_diameter = 70
human_speed = 10
recovery_duration = 500
infection_probablity = 0.4

# ----------------------------------------------------------------------------
[simulation]
time_step = 1
bound_space = true
min_bound = -1000
max_bound = 1000
run_mechanical_interactions = true
show_simulation_step = false

# ----------------------------------------------------------------------------
[visualization]
export = false
live = false
export_interval = 1

    [[visualize_sim_object]]
    name = "Human"
    additional_data_members = [ "state_" ]
